name: Update Compose File

on:
  repository_dispatch:
    types: [update-compose]  # Custom event type

jobs:
  update-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.client_payload.branch }}  # Using payload from the dispatch event
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update docker-compose image tag
        id: update-compose
        run: |
          SERVICE="${{ github.event.client_payload.service }}"  # Using service from the dispatch payload
          VERSION="${{ github.event.client_payload.version }}"  # Using version from the dispatch payload
          FILE=docker-compose.yml

          echo "Updating service '$SERVICE' to version '$VERSION' in $FILE"

          # Save the original file checksum
          cp "$FILE" "$FILE.bak"

          # Attempt to update the image line
          sed -i "s|\(image: protegeproject/$SERVICE:\)[^[:space:]]*|\1$VERSION|" "$FILE"

          echo "Result:"
          grep "image: protegeproject/$SERVICE" "$FILE" || echo "No matching image line found."

          # Check if the file was actually changed
          if cmp -s "$FILE" "$FILE.bak"; then
            echo "No change made to docker-compose.yml."
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "docker-compose.yml updated."
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.update-compose.outputs.changed == 'true'
        run: |
          git config user.name "webprotege-bot"
          git config user.email "webprotege@users.noreply.github.com"

          git add docker-compose.yml
          git commit -m "chore: bump ${{ github.event.client_payload.service }} to ${{ github.event.client_payload.version }}"
          git push origin ${{ github.event.client_payload.branch }}
